url: https://linhdoancong.github.io/
baseurl: https://linhdoancong.github.io/

# Site settings
title: Personal information
email: linhdoancong@gmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Ca Ngô
  pic: 1
  position: Project Manager
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Tiếp Nguyễn
  pic: 2
  position: Project Manager
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Kim Kim
  pic: 3
  position: Leader Android
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Sơn Nguyễn
  pic: 4
  position: Leader Designer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Việt Vũ
  pic: 5
  position: Leader Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Khoa Vũ
  pic: 6
  position: Leader Data
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/princevampirevn
  - title: facebook
    url: https://www.facebook.com/princevampirevn
  - title: linkedin
    url: https://www.linkedin.com/in/princevampirevn/
  - title: bitbucket 
    url: https://bitbucket.org/doanconglinh
  - title: github
    url: https://github.com/linhdoancong

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty